name: start release process
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub releaseF
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Create pull request for develop branch
        uses: repo-sync/pull-request@v2
        with:
          id: open-develop-pr
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: master
          destination_branch: develop
          pr_title: ${{ steps.tag_version.outputs.new_tag }} into develop
          pr_body: |
            ${{ steps.tag_version.outputs.changelog }}
          pr_label: "automated pr"

      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
