name: test workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of branch"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic # Need an `id` for output variables
        with:
          dry_run: false
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'master', 
              'next', 
              'next-major', 
              {
                name: 'beta', 
                prerelease: true
              }, 
              {
                name: 'alpha', 
                prerelease: true
              }
            ]

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}
